export const SUPABASE_URL = 'https://xkhulybdrxdzakarivvi.supabase.co';
export const SUPABASE_ANON_KEY = 'sb_publishable_NtOLOeDOCn3w2faTU4m8Ow_4iUhcVkM';
export const EDGE_FUNCTION_URL = 'https://xkhulybdrxdzakarivvi.supabase.co/functions/v1/claude';
export const VAPID_PUBLIC_KEY = 'BOJT9sBVkyJ8O7OO3dFqGUxFXqgyNaHqDnbSOmJajDY6s0K350HTgoyddWh3qkeeZyi7Kt4cfmqH_F5hNLfxOb4';
export const CLAUDE_MODEL = 'claude-sonnet-4-20250514';
export const MAX_TOKENS = 1000;
export const AYA_EMAILS = ['aya.test@gmail.com', 'marwan.test@gmail.com', 'test@test.com', 'ayamariner@gmail.com'];
export const APP_VERSION = '2.0.0';
export const JUNE_5_2026 = new Date('2026-06-05T00:00:00');
